Tp/add containers for commits

diff --git a/ci/Dockerfile b/ci/Dockerfile
--- a/ci/Dockerfile
+++ b/ci/Dockerfile
@@ -3,6 +3,7 @@ FROM golang:1.20
 
 ENV DOCKER_CHANNEL stable
 ENV DOCKER_VERSION 24.0.2
+ENV DOCKER_BUILDX_VERSION 0.11.1
 ENV GOLANGCI_LINT_VERSION v1.53.3
 
 # Install golint
@@ -42,3 +43,30 @@ RUN set -eux; \
     rm docker.tgz; \
     \
     docker --version
+
+# Install docker buildx
+
+RUN set -eux; \
+    \
+    apkArch="$(arch)"; \
+    case "$apkArch" in \
+    # amd64
+    x86_64) dockerArch='amd64' ;; \
+    # arm32v6
+    armhf) dockerArch='arm-v6' ;; \
+    # arm32v7
+    armv7) dockerArch='arm-v7' ;; \
+    # arm64v8
+    aarch64) dockerArch='arm64' ;; \
+    *) echo >&2 "error: unsupported architecture ($apkArch)"; exit 1 ;;\
+    esac; \
+    \
+    if ! wget -O docker-buildx "https://github.com/docker/buildx/releases/download/v${DOCKER_BUILDX_VERSION}/buildx-v${DOCKER_BUILDX_VERSION}.linux-${dockerArch}"; then \
+    echo >&2 "error: failed to download 'buildx-${DOCKER_BUILDX_VERSION}' for '${dockerArch}'"; \
+    exit 1; \
+    fi; \
+    \
+    mkdir -p /usr/local/lib/docker/cli-plugins; \
+    mv docker-buildx /usr/local/lib/docker/cli-plugins; \
+    chmod +x /usr/local/lib/docker/cli-plugins/docker-buildx; \
+    docker buildx version
